/* Generated by scripts/generate-theme-tokens.mjs. Do not edit. */

export const themeIds = [
  "base",
  "ember",
  "hearth",
  "meadow",
  "noir",
  "signal"
] as const;

export type ThemeId = (typeof themeIds)[number];

export const defaultThemeId: ThemeId = "base";

export const themeNames: Readonly<Record<ThemeId, string>> = {
  "base": "Base",
  "ember": "Ember",
  "hearth": "Hearth",
  "meadow": "Meadow",
  "noir": "Noir",
  "signal": "Signal"
};
